spring: 
  profiles: 
    active: 
    - dev
---
server: 
  port: 7001
spring: 
  profiles: dev 
  application:
    name: eureka-server-7001 
eureka:
  instance:
    hostname: eureka7001.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
---
server:
  port: 8001
spring:
  profiles: test
  application:
    name: eureka-server-7001 
eureka:
  instance:
    hostname: eureka7001.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/